### ISSUE TITLE
Bug report: Certain profile screenshots have minor issues

### ISSUE THREAD

**Issue by Lakshrp112** [roypriyanshu02/impressive-profile-readmes#9]
**A brief summary of the bug**

I have noticed some minor issues with certain profile screenshots. For instance, the profile screenshot for "oyepriyansh" is in dark mode while others are in white mode, creating inconsistency. Additionally, some profile screenshots, like that of "gargakshit," appear small in height, which can appear awkward on certain devices with different resolutions. I know that the screenshot height issue has already been resolved with the recent commit (d88749b), but the old screenshots have not been updated.

**Comment by roypriyanshu02** [comment]
Thank you for bringing these issues to our attention! Would you mind creating a pull request by deleting the screenshots from the screenshots directory? This will trigger the GitHub workflow to update the screenshots.
